[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/v1/*"
  to = "https://openapi.naver.com/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
